/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/hello-world/index.vue')['default']
    WmCharts: typeof import('./src/components/wm/charts/index.vue')['default']
    WmVocCheckbox: typeof import('./src/components/wm/voc/checkbox/index.vue')['default']
    WmVocCheckboxPropForm: typeof import('./src/components/wm/voc/checkbox/prop-form.vue')['default']
    WmVocCheckboxStat: typeof import('./src/components/wm/voc/checkbox/stat.vue')['default']
    WmVocInfo: typeof import('./src/components/wm/voc/info/index.vue')['default']
    WmVocInfoPropForm: typeof import('./src/components/wm/voc/info/prop-form.vue')['default']
    WmVocInput: typeof import('./src/components/wm/voc/input/index.vue')['default']
    WmVocInputPropForm: typeof import('./src/components/wm/voc/input/prop-form.vue')['default']
    WmVocParagraph: typeof import('./src/components/wm/voc/paragraph/index.vue')['default']
    WmVocParagraphPropForm: typeof import('./src/components/wm/voc/paragraph/prop-form.vue')['default']
    WmVocRadio: typeof import('./src/components/wm/voc/radio/index.vue')['default']
    WmVocRadioPropForm: typeof import('./src/components/wm/voc/radio/prop-form.vue')['default']
    WmVocRadioStat: typeof import('./src/components/wm/voc/radio/stat.vue')['default']
    WmVocTextarea: typeof import('./src/components/wm/voc/textarea/index.vue')['default']
    WmVocTextareaPropForm: typeof import('./src/components/wm/voc/textarea/prop-form.vue')['default']
    WmVocTitle: typeof import('./src/components/wm/voc/title/index.vue')['default']
    WmVocTitlePropForm: typeof import('./src/components/wm/voc/title/prop-form.vue')['default']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSpace: typeof import('element-plus/es')['ElSpace']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const HelloWorld: typeof import('./src/components/hello-world/index.vue')['default']
  const WmCharts: typeof import('./src/components/wm/charts/index.vue')['default']
  const WmVocCheckbox: typeof import('./src/components/wm/voc/checkbox/index.vue')['default']
  const WmVocCheckboxPropForm: typeof import('./src/components/wm/voc/checkbox/prop-form.vue')['default']
  const WmVocCheckboxStat: typeof import('./src/components/wm/voc/checkbox/stat.vue')['default']
  const WmVocInfo: typeof import('./src/components/wm/voc/info/index.vue')['default']
  const WmVocInfoPropForm: typeof import('./src/components/wm/voc/info/prop-form.vue')['default']
  const WmVocInput: typeof import('./src/components/wm/voc/input/index.vue')['default']
  const WmVocInputPropForm: typeof import('./src/components/wm/voc/input/prop-form.vue')['default']
  const WmVocParagraph: typeof import('./src/components/wm/voc/paragraph/index.vue')['default']
  const WmVocParagraphPropForm: typeof import('./src/components/wm/voc/paragraph/prop-form.vue')['default']
  const WmVocRadio: typeof import('./src/components/wm/voc/radio/index.vue')['default']
  const WmVocRadioPropForm: typeof import('./src/components/wm/voc/radio/prop-form.vue')['default']
  const WmVocRadioStat: typeof import('./src/components/wm/voc/radio/stat.vue')['default']
  const WmVocTextarea: typeof import('./src/components/wm/voc/textarea/index.vue')['default']
  const WmVocTextareaPropForm: typeof import('./src/components/wm/voc/textarea/prop-form.vue')['default']
  const WmVocTitle: typeof import('./src/components/wm/voc/title/index.vue')['default']
  const WmVocTitlePropForm: typeof import('./src/components/wm/voc/title/prop-form.vue')['default']
}