/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/wm/editor/header.vue')['default']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    Icon: typeof import('./src/components/wm/icon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/wm/editor/toolbar.vue')['default']
    WmEditorComponentLib: typeof import('./src/components/wm/editor/component-lib.vue')['default']
    WmEditorComponentProp: typeof import('./src/components/wm/editor/component-prop.vue')['default']
    WmEditorHeader: typeof import('./src/components/wm/editor/header.vue')['default']
    WmEditorLayer: typeof import('./src/components/wm/editor/layer.vue')['default']
    WmEditorLeftPanel: typeof import('./src/components/wm/editor/left-panel.vue')['default']
    WmEditorMainCanvas: typeof import('./src/components/wm/editor/main-canvas.vue')['default']
    WmEditorPageSettings: typeof import('./src/components/wm/editor/page-settings.vue')['default']
    WmEditorRightPanel: typeof import('./src/components/wm/editor/right-panel.vue')['default']
    WmEditorToolbar: typeof import('./src/components/wm/editor/toolbar.vue')['default']
    WmIcon: typeof import('./src/components/wm/icon/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Header: typeof import('./src/components/wm/editor/header.vue')['default']
  const HelloWorld: typeof import('./src/components/hello-world.vue')['default']
  const Icon: typeof import('./src/components/wm/icon/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toolbar: typeof import('./src/components/wm/editor/toolbar.vue')['default']
  const WmEditorComponentLib: typeof import('./src/components/wm/editor/component-lib.vue')['default']
  const WmEditorComponentProp: typeof import('./src/components/wm/editor/component-prop.vue')['default']
  const WmEditorHeader: typeof import('./src/components/wm/editor/header.vue')['default']
  const WmEditorLayer: typeof import('./src/components/wm/editor/layer.vue')['default']
  const WmEditorLeftPanel: typeof import('./src/components/wm/editor/left-panel.vue')['default']
  const WmEditorMainCanvas: typeof import('./src/components/wm/editor/main-canvas.vue')['default']
  const WmEditorPageSettings: typeof import('./src/components/wm/editor/page-settings.vue')['default']
  const WmEditorRightPanel: typeof import('./src/components/wm/editor/right-panel.vue')['default']
  const WmEditorToolbar: typeof import('./src/components/wm/editor/toolbar.vue')['default']
  const WmIcon: typeof import('./src/components/wm/icon/index.vue')['default']
}